version: 2.1

jobs:
  build:
    docker:
      - image: nixos/nix:2.11.1
    steps:
      - checkout
      - run:
          name: Run sbt tests
          command: nix-shell shell.nix --pure --run "sbt test"

workflows:
  basic-workflow:
    jobs:
      - build
