version: 2.1

jobs:
  build:
    docker:
      - image: nixos/nix:2.11.1
    steps:
      - checkout
      - run:
          name: Run sbt tests
          # # nix-env -iA nixpkgs.cachix nixpkgs.bash
          command: |
            nix-shell shell.nix --pure --run "sbt test"

      #- run: cachix watch-exec $CACHIX_NAME nix-build
      #- run: cachix watch-exec $CACHIX_NAME nix-shell --run "echo nix-shell successfully entered"

#jobs:
#  say-hello:
#    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
#    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
#    docker:
#      - image: cimg/base:stable
#    # Add steps to the job
#    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
#    steps:
#      - checkout
#      - run:
#          name: "Say hello"
#          command: "echo Hello, World!"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - build
